const ALERT = 'ALERT';
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

export { REFETCH_CHATS, ALERT, NEW_MESSAGE_ALERT, NEW_ATTACHMENT }